### ISSUE TITLE
Cleaning dependencies on SVN

### ISSUE THREAD

**Issue by olivhoenen** [psnc-apps/muscle2#3]
I've notice a few parts of the sources or the build process which are still depending on SVN, we should adapt these to GIT or simply drop these part if they do not make sense anymore. Here are first items but there might be more:

-  build/build.sh: starts with a "svn up" to make sure wc is up to date (=> also this can cause issues in platforms where access to the outside world is not permitted)

- src/java/muscle/Version.java: usage of svn:keywords there

**Comment by bartoszbosak** [comment]
The code has been updated to use info from git instead of SVN kewords. Since git does not provide keywords, now the information about specific version is loaded from generated properties file.
