### ISSUE TITLE
Ruby dependency: which version?

### ISSUE THREAD

**Issue by olivhoenen** [psnc-apps/muscle2#5]
Hi, in the installation section here on github wiki there is no mention to ruby version required to use properly muscle. In previous installation page (http://apps.man.poznan.pl/trac/muscle/wiki/Installation) it was mentioned that Ruby 1.8.x requires additional install of json GEM, but Ruby 1.9.x and 2.0.x might not and should work directly out from the box. This is apparently not true with some 2.0 versions where 'iconv' (required in share/muscle/ruby/json/common.rb) which has been deprecated in version 1.9 has already disappear.

**Comment by bartoszbosak** [comment]
Hi all, I think I've resolved this problem by replacing the old json library with the new one. The new library doesn't use iconv any more. The simple tests work fine, but in case of problems we will need to improve the solution.
